// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Coins, CoinsTableId } from "./tables/Coins.sol";
import { Claimed, ClaimedTableId } from "./tables/Claimed.sol";
