// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Tasks, TasksData, TasksTableId } from "./tables/Tasks.sol";
import { Claims, ClaimsTableId } from "./tables/Claims.sol";
