// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IClaimsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClaimsSystem {
  function claim(address collection, uint32 tokenid) external;
}
